# Generated by Django 5.1.4 on 2024-12-12 10:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('content', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='sections/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('site_logo', models.ImageField(upload_to='site/')),
                ('favicon', models.ImageField(upload_to='site/')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('google_maps_embed', models.TextField(help_text='Paste your Google Maps embed code here')),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('hero_title', models.CharField(max_length=200)),
                ('hero_subtitle', models.CharField(max_length=200)),
                ('hero_video', models.FileField(blank=True, upload_to='site/videos/')),
                ('about_title', models.CharField(max_length=200)),
                ('about_content', ckeditor.fields.RichTextField()),
                ('about_image', models.ImageField(upload_to='site/')),
                ('footer_text', ckeditor.fields.RichTextField()),
                ('meta_description', models.TextField()),
                ('meta_keywords', models.TextField()),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
