# Generated by Django 5.1.4 on 2024-12-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_homepagesection_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(choices=[('fa-bolt', 'Bolt'), ('fa-fire', 'Fire'), ('fa-cog', 'Cog'), ('fa-tools', 'Tools'), ('fa-wrench', 'Wrench'), ('fa-hammer', 'Hammer'), ('fa-industry', 'Industry'), ('fa-hard-hat', 'Hard Hat'), ('fa-truck', 'Truck'), ('fa-ruler', 'Ruler'), ('fa-drafting-compass', 'Compass'), ('fa-layer-group', 'Layers')], max_length=50),
        ),
    ]
